target = "https://www.luogu.com.cn/api/discuss?forum=relevantaffairs&page=1"

[time_interval]
mainpage = 30
delat_time_normal = 500
delay_time_error = 1000

[database]
url = "xxx"
nae = "luogulo"

[request]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
cookie = "__client_id=ecc0411dcb292a186d3278a52f2c90ac08cf260c; login_referer=https%3A%2F%2Fwww.luogu.com.cn%2F; _uid=111047"
host = "www.luogu.com.cn"

[http]
port = 9000
access_origin = "*"

[functions]
autosave = false
web = true